# Generated by Django 4.2.7 on 2023-12-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sswebsite', '0002_alter_certificate_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='user',
            new_name='Users',
        ),
    ]
