# Generated by Django 4.2.7 on 2023-12-08 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sswebsite', '0003_rename_user_certificate_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
