# Generated by Django 4.2.7 on 2023-12-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswebsite', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_desc',
            field=models.TextField(default=''),
        ),
    ]
