# Generated by Django 5.0.1 on 2024-01-15 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sswebsite', '0008_userprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
    ]
