# Generated by Django 5.0.1 on 2024-01-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswebsite', '0011_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='gitLink',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='links',
            name='linkedInLink',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='links',
            name='otherLink',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='links',
            name='portfolioLink',
            field=models.URLField(),
        ),
    ]
